[package]
name = "livecoding"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
  "hot-reload",
  "shared",
  "view",
]

[dependencies]
hot-reload = { path = "hot-reload" }
shared = { path = "shared" }
druid = { path = "../druid/druid"}


[[bin]]
name = "app"
path = "app/main.rs"
