[package]
name = "hot-reload"
version = "0.1.0"
authors = ["Maan2003 <Manmeetmann2003@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.6.5"
notify = "5.0.0-pre.4"
rand = "0.7.3"
