[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[dependencies]
druid= { path = "../../druid/druid", default-features=false }
# druid= { git = "https://github.com/linebender/druid", default-features=false, features=['x11'] }

