[package]
name = "view"
version = "0.1.0"
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
druid = { git = 'https://github.com/linebender/druid', default-features = false }
shared = { path = "../shared" }
